# Nixpacks config to deploy only the backend service

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --prefix backend"
]

[phases.build]
cmds = [
  "npm run build --prefix backend"
]

[start]
cmd = "npm run start:prod --prefix backend"
