version: '3.8'

services:
  # PostgreSQL Database for testing
  postgres-test:
    image: postgres:15-alpine
    container_name: synctask-postgres-test
    restart: "no"
    environment:
      POSTGRES_DB: synctask_test_db
      POSTGRES_USER: synctask
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - synctask-test-network

  # Redis for testing
  redis-test:
    image: redis:7-alpine
    container_name: synctask-redis-test
    restart: "no"
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - synctask-test-network

volumes:
  postgres_test_data:
  redis_test_data:


networks:
  synctask-test-network:
    driver: bridge
