version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:15-alpine
    container_name: synctask-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: synctask_db
      POSTGRES_USER: synctask
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - synctask-dev-network

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: synctask-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synctask-dev-network

  # Database admin interface
  adminer:
    image: adminer:4.8.1
    container_name: synctask-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - synctask-dev-network

volumes:
  postgres_data:
  redis_data:


networks:
  synctask-dev-network:
    driver: bridge
