services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: synctask-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: synctask_db
      POSTGRES_USER: synctask
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - synctask-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: synctask-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - synctask-network

volumes:
  postgres_data:
  redis_data:


networks:
  synctask-network:
    driver: bridge
