name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Start database
        run: npm run start:db

      - name: Run Prisma migrations
        run: npx prisma migrate deploy --schema backend/prisma/schema.prisma

      - name: Build backend
        run: npm run build:backend

      - name: Start backend
        run: npm run dev:backend &
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Wait for backend
        run: npx wait-on http://localhost:3001/api/health --timeout 30000

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E tests
        run: npx playwright test
        working-directory: backend

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: backend/playwright-report/
          retention-days: 30
